export const homeActions = [
  {
    key: "view_inventory",
    title: "View Inventory",
    description: "Check material quantities and locations.",
    icon: "📦",
    path: "/inventory",
    permission: "view_inventory",
  },
  {
    key: "enter_purchase_order",
    title: "Enter Purchase Order",
    description: "Capture purchase orders before receiving inventory.",
    icon: "🧾",
    path: "/enter-purchase-order",
    permission: "upload_purchase_orders",
  },
  {
    key: "request_material",
    title: "Request Material",
    description: "Submit a material request.",
    icon: "📝",
    path: "/request-material",
    permission: "request_material",
  },
  {
    key: "pending_requests",
    title: "Pending Requests",
    description: "Review and approve material requests.",
    icon: "✅",
    path: "/pending-requests",
    permission: "approve_requests",
  },
  {
    key: "manifest_inventory",
    title: "Manifest Inventory",
    description: "Build a manifest from an approved request.",
    icon: "📋",
    path: "/manifest-inventory",
    permission: "manifest_inventory",
  },
  {
    key: "transfer_inventory",
    title: "Transfer Inventory",
    description: "Execute shipment and receipt for finalized manifests.",
    icon: "🔄",
    path: "/transfer-inventory",
    permission: "transfer_inventory",
  },
  {
    key: "receive_inventory",
    title: "Receive Inventory",
    description: "Log incoming materials.",
    icon: "🚚",
    path: "/receive-inventory",
    permission: "receive_inventory",
  },
  {
    key: "shipment_tracking",
    title: "Shipment Tracking",
    description: "Track request and shipment workflow status.",
    icon: "📉",
    path: "/shipment-tracking",
    permission: "track_shipment",
  },
  {
    key: "admin_tools",
    title: "Admin Tools",
    description: "Manage users and settings.",
    icon: "⚙️",
    path: "/admin-tools",
    permission: "manage_users",
  },
]

export const adminToolActions = [
  {
    key: "manage_users",
    title: "Manage Users",
    description: "Create, update, and manage user access.",
    icon: "👥",
    path: "/manage-users",
    permission: "manage_users",
  },
  {
    key: "manage_locations",
    title: "Manage Locations",
    description: "Maintain warehouse and site locations.",
    icon: "📌",
    path: "/manage-locations",
    permission: "manage_locations",
  },
  {
    key: "manage_projects",
    title: "Manage Projects",
    description: "Maintain project records and assignments.",
    icon: "🗂️",
    path: "/manage-projects",
    permission: "manage_projects",
  },
  {
    key: "audit_log",
    title: "Audit Log",
    description: "Review every state change across the system.",
    icon: "📜",
    path: "/audit-log",
    permission: "view_audit_log",
  },
]