BEGIN;

ALTER TABLE locations
  ADD COLUMN IF NOT EXISTS address_line_1 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_line_2 TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS state TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS postal_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS poc_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS poc_phone TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS poc_email TEXT NOT NULL DEFAULT '';

COMMIT;
